languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "雷系鈴鐺研究所"
contentDir = "content/zh-tw"
hasCJKLanguage = true

[params]
  displayName = "中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006/01/02"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "本研究所專注於研究提升毛毛在外奔波的生活品質！\n希望透過小東西的輔助，讓毛毛散播更多快樂給世界的大家！"
  # copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "雷系鈴鐺研究所"
   image = "img/logo.png"
   headline = "本研究所專注於研究提升毛毛在外奔波的生活品質！讓毛毛散播更多快樂給世界的大家！"
   bio = "A little bit about you"
   links = [
     { email = "mailto:raibelllab@gmail.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/raibelllab" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/raibelllab" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
     { x-twitter = "https://twitter.com/raibelllab" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
   ]
